version: '3'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "user"
      MYSQL_DATABASE: "mailMoverDB"
    expose:
      - "3306"
  acp_frontend:
    build:
      context: ./mail-mover/acp frontend/acp-frontend
      dockerfile: Dockerfile
    ports:
      - 4001:3000
  admin_frontend:
    build:
      context: ./mail-mover/admin frontend/admin-frontend
      dockerfile: Dockerfile
    ports:
      - 4000:3000
  store_frontend:
    build:
      context: ./store/frontend/store-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  mail_mover_backend:
    build:
      context: ./mail-mover/backend/mailMoverPlatform
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
  store_backend:
    build:
      context: ./store/backend/storebackend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
 